/**
 * The count a `CharCounter` shows — display only (Stage 04 PRD §15.2 rule 6,
 * §15.5 item 1). The verdict on a length is the linter's, through
 * `POST /creative-runs/{id}/lint-preview`; this only says the number the
 * linter will measure, so `27/30` beside a headline is the server's 27.
 *
 * It mirrors, and only mirrors, two server functions:
 * - `guardrails.matchers.assets.measure(text, "chars")` — Python's `len()`,
 *   i.e. Unicode code points: one per emoji code point, one per CJK
 *   character, never UTF-16 units (`"🧪".length` is 2; the server says 1);
 * - `creative.edits.linted_text(surface, text)` — an RSA headline is measured
 *   on its keyword-insertion default (4.2.1's `measured_text`), a malformed
 *   insertion as written, every other surface as written.
 *
 * `lib/creative/char-count.test.mjs` holds it to the server for 200 strings
 * (`tests/fixtures/char-count-parity.json`, generated by the api from the
 * linter itself). No imports, so node can run that test on this file as is.
 */

/** `agent.schemas.search_ads.DKI_TOKENS`: the capitalisations Google performs. */
const DKI_TOKENS = new Set(["keyword", "Keyword", "KeyWord", "KEYWord", "KeyWORD"]);

/** `agent.nodes.creative.n4_2_1_headline_spread.SURFACE`. */
const HEADLINE_SURFACE = "rsa_headline";

/**
 * Python's `str.isspace()` — what `str.strip()` removes when the server judges
 * an insertion's default empty. Not `\s`: JavaScript also strips U+FEFF and
 * keeps U+001C–U+001F and U+0085, and either difference changes a count.
 */
const PY_WHITESPACE = new Set([
  "\t", "\n", "\v", "\f", "\r", "\u001c", "\u001d", "\u001e", "\u001f", " ", "\u0085",
  " ", " ", " ", " ", " ", " ", " ", " ", " ",
  " ", " ", " ", " ", " ", " ", " ", " ", "　",
]);

function isBlank(text: string): boolean {
  for (const character of text) {
    if (!PY_WHITESPACE.has(character)) return false;
  }
  return true;
}

function occurrences(text: string, character: string): number {
  let found = 0;
  for (const c of text) if (c === character) found += 1;
  return found;
}

/**
 * `search_ads.render_default`: the headline with its one insertion replaced
 * by the default, the text itself without one, or `null` where the server
 * raises `DkiError` (unbalanced braces, an insertion Google does not perform,
 * two insertions, an empty default).
 */
function renderDefault(text: string): string | null {
  const tokens = [...text.matchAll(/\{([^{}]*)\}/g)];
  if (occurrences(text, "{") !== tokens.length || occurrences(text, "}") !== tokens.length) {
    return null;
  }
  const [token] = tokens;
  if (token === undefined) return text;
  for (const found of tokens) {
    const inner = found[1] ?? "";
    const colon = inner.indexOf(":");
    if (colon < 0 || !DKI_TOKENS.has(inner.slice(0, colon))) return null;
  }
  if (tokens.length > 1) return null;
  const inner = token[1] ?? "";
  const fallback = inner.slice(inner.indexOf(":") + 1);
  if (isBlank(fallback)) return null;
  return text.slice(0, token.index) + fallback + text.slice(token.index + token[0].length);
}

/** `creative.edits.linted_text`: the text the linter measures on `surface`. */
export function measuredText(surface: string, text: string): string {
  if (surface !== HEADLINE_SURFACE) return text;
  return renderDefault(text) ?? text;
}

/** The server's count of `text` on `surface`, in the spec sheet's unit (`chars`). */
export function charCount(surface: string, text: string): number {
  // A string iterates by code point, which is what Python's len() counts.
  return Array.from(measuredText(surface, text)).length;
}
