"use client";

import { useVirtualizer } from "@tanstack/react-virtual";
import { ImageOff } from "lucide-react";
import { memo, useLayoutEffect, useMemo, useRef, useState, type RefObject } from "react";

import { LintChip } from "@/components/creative/lint-chip";
import { LetterboxFrame } from "@/components/creative/media-frame";
import { Badge } from "@/components/ui/badge";
import { mediaContentUrl } from "@/lib/api/media-library";
import {
  DERIVATION_LABEL,
  bytesOfLimit,
  columnsFor,
  gridRows,
  pxLabel,
  ratioValue,
  type FileTile,
  type GapTile,
  type SurfaceGroup,
} from "@/lib/creative/media-library";
import { cn } from "@/lib/utils";

const GAP_PX = 12;
const HEADER_PX = 44;
/** Four lines of label under each frame: ratio and size, bytes, two chip rows. */
const LABEL_PX = 96;

/** Plain, as law 3 wants it: the words, and the model on hover. */
export function AiGeneratedChip({ model }: { model: string | null }) {
  return (
    <span title={model ? `Generated by ${model}` : "Generated by a media model"} className="inline-flex">
      <Badge>AI-generated</Badge>
    </span>
  );
}

/**
 * `RenditionGrid` (Stage 04 PRD §15.4 G): every rendition, fitted logo and gap
 * of 4.4.3, grouped by surface, as aspect-true tiles — each file letterboxed
 * on the checkerboard at its real ratio, never cropped to fill — labelled with
 * ratio, pixels, `bytes/limit`, derivation and lint. A gap is a dashed outline
 * of the shape that is missing, with the server's reason.
 *
 * §15.5 item 2: a tile is the file's WebP proxy (`variant=preview`), lazy and
 * async-decoded, and only the rows near the viewport exist at all — 500 tiles
 * scroll inside one frame budget. A tile never falls back to the master: a
 * file with no proxy says so, and the drawer is where the file itself loads.
 */
export function RenditionGrid({
  groups,
  scrollRef,
  models,
  onOpen,
}: {
  groups: SurfaceGroup[];
  /** The element that scrolls — the virtualiser listens to it. */
  scrollRef: RefObject<HTMLElement | null>;
  /** Job id → the model that painted it, for the `AI-generated` chip. */
  models: Map<string, string>;
  onOpen: (tile: FileTile) => void;
}) {
  const wrapper = useRef<HTMLDivElement>(null);
  const [width, setWidth] = useState(0);
  const [margin, setMargin] = useState(0);

  useLayoutEffect(() => {
    const node = wrapper.current;
    const scroller = scrollRef.current;
    if (!node || !scroller) return;
    const measure = () => {
      setWidth(node.clientWidth);
      setMargin(node.getBoundingClientRect().top - scroller.getBoundingClientRect().top + scroller.scrollTop);
    };
    measure();
    const observer = new ResizeObserver(measure);
    observer.observe(node);
    return () => observer.disconnect();
  }, [scrollRef]);

  const minTile = width < 480 ? 150 : 176;
  const columns = width > 0 ? columnsFor(width, minTile, GAP_PX) : 1;
  const tileWidth = width > 0 ? (width - GAP_PX * (columns - 1)) / columns : minTile;
  const rowPx = tileWidth + LABEL_PX + GAP_PX + 8;
  const rows = useMemo(() => gridRows(groups, columns), [groups, columns]);

  const virtualizer = useVirtualizer({
    count: rows.length,
    getScrollElement: () => scrollRef.current,
    estimateSize: (index) => (rows[index]?.kind === "header" ? HEADER_PX : rowPx),
    overscan: 4,
    scrollMargin: margin,
    getItemKey: (index) => rows[index]?.key ?? index,
  });

  useLayoutEffect(() => {
    virtualizer.measure();
  }, [virtualizer, rowPx, columns]);

  return (
    <div ref={wrapper} data-testid="rendition-grid" data-columns={columns}>
      <div className="relative w-full" style={{ height: virtualizer.getTotalSize() }}>
        {virtualizer.getVirtualItems().map((item) => {
          const row = rows[item.index];
          if (!row) return null;
          return (
            <div
              key={item.key}
              data-index={item.index}
              className="absolute left-0 top-0 w-full"
              style={{ height: item.size, transform: `translateY(${item.start - margin}px)` }}
            >
              {row.kind === "header" ? (
                <GroupHeader group={row.group} />
              ) : (
                <div
                  className="grid"
                  style={{ gridTemplateColumns: `repeat(${columns}, minmax(0, 1fr))`, columnGap: GAP_PX }}
                >
                  {row.tiles.map((tile) =>
                    tile.kind === "file" ? (
                      <FileTileView
                        key={tile.key}
                        tile={tile}
                        model={tile.jobId ? (models.get(tile.jobId) ?? null) : null}
                        onOpen={onOpen}
                      />
                    ) : (
                      <GapTileView key={tile.key} tile={tile} />
                    ),
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

function GroupHeader({ group }: { group: SurfaceGroup }) {
  return (
    <div className="flex h-full items-end justify-between gap-3 border-b pb-2">
      <h3 className="text-sm font-semibold text-fg">{group.label}</h3>
      <p className="text-xs tabular-nums text-fg-muted">
        {group.files} {group.files === 1 ? "file" : "files"}
        {group.gaps > 0 ? ` · ${group.gaps} ${group.gaps === 1 ? "gap" : "gaps"}` : ""}
      </p>
    </div>
  );
}

const FileTileView = memo(function FileTileView({
  tile,
  model,
  onOpen,
}: {
  tile: FileTile;
  model: string | null;
  onOpen: (tile: FileTile) => void;
}) {
  const [missing, setMissing] = useState(false);
  const who = tile.conceptName ?? (tile.derivation === "composited" ? "Logo" : tile.campaignRef);
  return (
    <button
      type="button"
      onClick={() => onOpen(tile)}
      data-tile="file"
      data-key={tile.key}
      data-ratio={tile.ratio}
      data-px={tile.px}
      aria-label={`${who}, ${tile.ratio}, ${pxLabel(tile.px)}. Open the file`}
      className={cn(
        "group flex min-w-0 flex-col gap-2 rounded-token p-1 text-left",
        "transition-colors duration-150 ease-out hover:bg-surface-hover motion-reduce:transition-none",
        "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent",
      )}
    >
      <LetterboxFrame ratio={tile.width / tile.height}>
        {missing ? (
          <span className="grid size-full place-items-center bg-surface p-1 text-center text-xs text-fg-muted">
            <ImageOff className="size-4" aria-hidden />
            No preview proxy
          </span>
        ) : (
          // eslint-disable-next-line @next/next/no-img-element -- a signed, redirected file; next/image would re-encode it
          <img
            src={mediaContentUrl(tile.mediaId, "preview")}
            alt=""
            width={tile.width}
            height={tile.height}
            loading="lazy"
            decoding="async"
            draggable={false}
            onError={() => setMissing(true)}
            className="block size-full object-contain"
          />
        )}
      </LetterboxFrame>
      <span className="flex h-24 min-w-0 flex-col gap-1 overflow-hidden text-xs">
        <span className="flex min-w-0 items-baseline justify-between gap-2">
          <span className="font-medium tabular-nums text-fg">{tile.ratio}</span>
          <span className="truncate tabular-nums text-fg-muted">{pxLabel(tile.px)}</span>
        </span>
        <span className="truncate tabular-nums text-fg-muted" title={who}>
          {bytesOfLimit(tile.bytes, tile.maxBytes)}
        </span>
        <span className="flex flex-wrap items-center gap-1">
          <Badge>{DERIVATION_LABEL[tile.derivation]}</Badge>
          <LintChip verdict={tile.lint} />
          {tile.generated ? <AiGeneratedChip model={model} /> : null}
        </span>
      </span>
    </button>
  );
});

const GapTileView = memo(function GapTileView({ tile }: { tile: GapTile }) {
  const ratio = ratioValue(tile.ratio) ?? 1;
  return (
    <div
      role="group"
      aria-label={`No ${tile.ratio} file${tile.conceptName ? ` for ${tile.conceptName}` : ""}: ${tile.why}`}
      data-tile="gap"
      data-key={tile.key}
      data-ratio={tile.ratio}
      className="flex min-w-0 flex-col gap-2 p-1"
    >
      <LetterboxFrame ratio={ratio} dashed className="bg-surface">
        <span className="grid size-full place-items-center p-1 text-center text-xs font-medium tabular-nums text-fg-muted">
          {tile.ratio}
        </span>
      </LetterboxFrame>
      <span className="flex h-24 min-w-0 flex-col gap-1 overflow-hidden text-xs">
        <span className="font-medium text-fg">Not made · gap</span>
        <span className="line-clamp-4 text-fg-muted" title={tile.why}>
          {tile.why}
        </span>
      </span>
    </div>
  );
});
